name: Build Torque Test Report
description: Upload Torques unit test artifact.
inputs:
    name:
        description: The name of the unit test.
        default: "${{github.job}}"
    artifact-name:
        description: The name of the artifact.
        required: true
    path:
        description: The path to the upload.
        required: true
        default: "**/My Projects/Torque3D/game/test_detail.xml"
runs:
  using: "composite"
  steps:
    - name: Test Reporter
      uses: phoenix-actions/test-reporting@v12
      with:
        artifact: ${{inputs.artifact-name}}
        name: ${{inputs.name}}
        path: ${{inputs.path}}
        reporter: java-junit 