name: Upload Torque Test Report
description: Upload Torques unit test artifact.
inputs:
    name:
        description: The name of the unit test.
        default: "${{github.job}}"
    path:
        description: The path to the upload.
        required: true
        default: "**/My Projects/Torque3D/game/test_detail.xml"
runs:
    using: "composite"
    steps:
      - name: Upload Torque Test Report
        uses: actions/upload-artifact@v3.1.2
        with:
            name: ${{inputs.name}}
            path: ${{inputs.path}}
            retention-days: 1
